<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\FinAdvisor.BuildingBlocks.Application\FinAdvisor.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\FinAdvisor.BuildingBlocks.Domain\FinAdvisor.BuildingBlocks.Domain.csproj" />
    <ProjectReference Include="..\FinAdvisor.Modules.Identity.Domain\FinAdvisor.Modules.Identity.Domain.csproj" />
  </ItemGroup>

</Project>
